config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"}



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

#   get "/users/sign_up", to: "users#new"

   resources :users, only: [:index,:show] do
     resources :posts ,only: [:index,:show,:edit,:new,:create]
   end

   resources :posts, only: [:index,:destroy] do
     resources :comments, :likes , only: [:new,:create,:destroy]
   end

   namespace :api do
    resources :users do
      resources :posts, only: [:index,:show] do
        resources :comments
      end
    end
   end
 end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'
  validates :text, presence: true, length: { minimum: 3, maximum: 255 }

  # A method which returns the 5 most recent comments for a given post.
  scope :recent_posts_comment, ->(post) { where(post:).order(created_at: 'DESC').first(5) }

  # A method that updates the comments counter for a post.
  scope :update_comments_counter, ->(post, counter) { Post.update_comments_counter(post, counter) }
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApiController
  def index
    @comments = Comment.includes(:author, :post).where(author: { id: params[:user_id] }, post: { id: params[:post_id] })
    render json: @comments
  end

  def create
    @comment = Comment.new(params.require(:comment).permit(:text, :post_id, :author_id))
    if @comment.save
      head :created
    else
      head :bad_request
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def update_comments_counter(post)
    comments_counter = Post.find_comments_amount(post.id).map(&:comments_counter)
    comments_counter = comments_counter[0]
    comments_counter = if comments_counter.nil?
                         1
                       else
                         comments_counter + 1
                       end
    Post.update_comments_counter(post.id, comments_counter)
  end

  def create
    @comment = Comment.new(params.require(:new_comment).permit(:text))
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    # Increase Comments Counter
    update_comments_counter(Post.find(params[:post_id]))

    respond_to do |format|
      format.html do
        if @comment.save
          flash[:success] = 'comment successfully created'
          redirect_to user_post_path(@comment.author.id, params[:post_id])
        else
          flash[:error] = 'Something went wrong one or more field is empty'
          comment = Comment.new
          @user = current_user
          respond_to do |f|
            f.html { redirect_to request.referrer, locals: { comment: } }
          end
        end
      end
    end
  end

  def new
    comment = Comment.new
    @user = current_user
    respond_to do |f|
      f.html { render 'new', locals: { comment: } }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path, status: :see_other
  end
end

app/views/comments/_comment.html.erb
    <div class="comments-list-container">
        <span class="commenter-user-name">Username: <%= comment.author.name %></span>
        <p class="comments-content">Comment: <%= comment.text %></p>
        <% if can? :delete, comment %>
            <%= link_to 'Delete', post_comment_path(comment.post_id,comment.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_confirm: "Are you sure?" },class: 'counter counter-btn' %>
        <% end %>
    </div>

app/views/comments/new.html.erb
<% flash.each do |type, msg| %>
  <% if type == "error" %>
    <div class="error-notice">
        <%= msg %>
    </div>
  <% end %>
<% end %>
<div class="form-container">
    <div class ="form-heading">
        <h3>Add New Comment</h3>
    <div>
    <%= form_with model: comment,method: :post, url: post_comments_path, scope: :new_comment,local:true do |form| %>
        <div>
            <%= form.label :text %>:
            <br>
            <%= form.text_area :text %>
        </div>
        <%= form.submit "Add comment", disable_with: 'Submiting...' %>
    <% end %>
<div>