config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"}



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

#   get "/users/sign_up", to: "users#new"

   resources :users, only: [:index,:show] do
     resources :posts ,only: [:index,:show,:edit,:new,:create]
   end

   resources :posts, only: [:index,:destroy] do
     resources :comments, :likes , only: [:new,:create,:destroy]
   end

   namespace :api do
    resources :users do
      resources :posts, only: [:index,:show] do
        resources :comments
      end
    end
   end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Authorization rules for cancancan
  ROLES = %i[admin moderator author banned].freeze

  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :posts_counter, presence: false, comparison: { greater_than_or_equal_to: 0 },
                            numericality: { only_integer: true }

  # This scope will find the amout of posts the user have and
  # it will try to reterive the informations by given author ID.
  scope :find_posts_amount, ->(id) { select(:posts_counter).where(id:) }

  # This method will take the authors Id as parameter, and updated count value
  # It will increment the posts_counter by the given count value the.
  def self.update_posts_counter(id, posts_counter)
    count = posts_counter
    User.where(id:).update(posts_counter: count)
  end

  # Here we can get posts that belongs to each user by just passing the ID of the author
  def recent_posts
    posts.order(created_at: 'DESC').first(3)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  def index
    @user = User.includes(posts: [:comments], likes: [:post])
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @btn = current_user == @user
    @posts = Post.includes(:author).where(author: { id: params[:id] }).order(created_at: 'DESC').first(3)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/views/users/_user.html.erb
<%= link_to user_path(user.id), class: 'user-link-container' do %>
<div class="user-list-container">
    <div class="user-image-container">
         <image class="user-photo" src="<%= user.photo %>"></image>
    </div>
    <div class="user-detail-container">
        <h3 class="user-name"><%= user.name %></h3>
        <span class="num-posts">Number of posts: <%= user.posts_counter %></span>
    </div>
</div>
<% end %>

app/views/users/index.html.erb
<div class="home-container">
<%= render @user %>
</div>

app/views/users/show.html.erb
<div class="home-container">
<% flash.each do |type, msg| %>
  <% if type == "success" %>
    <div class="success-notice">
            <%= msg %>
    </div>
  <% end %>
<% end %>

<%= render @user %>

<div class="user-detail-bio">
    <h4>Bio</h4>
    <p class="user-bio-content">
        <%= @user.bio %>
    </p>
    <%= link_to new_user_post_path(@user.id) do %>
    <% if @btn %>
    <div class="add-new-post">
        <button>Add New Post </button>
    </div>
    <% end %>
    <% end %>
</div>

<%= render @posts %>
<div class="btn-container-post">
<%= link_to user_posts_path(@user.id) do %>
<% if @user.posts.length != 0 %>
<button class="btn-posts">See all Posts</button>
<% end %>
<% end %>
</div>
</div>