config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root "users#index"
  devise_for :users, :controllers => {:registrations => "registrations"}



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

#   get "/users/sign_up", to: "users#new"

   resources :users, only: [:index,:show] do
     resources :posts ,only: [:index,:show,:edit,:new,:create]
   end

   resources :posts, only: [:index,:destroy] do
     resources :comments, :likes , only: [:new,:create,:destroy]
   end

   namespace :api do
    resources :users do
      resources :posts, only: [:index,:show] do
        resources :comments
      end
    end
   end
 end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { minimum: 1, maximum: 255 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  # Ths scope will find the amount of comments for post
  # it will try to reterive the informations by given Post ID.
  scope :find_comments_amount, ->(id) { select(:comments_counter).where(id:) }

  # This scope will find the current amount of likes a post have by the given Post ID.
  scope :find_likes_amount, ->(id) { select(:likes_counter).where(id:) }

  # This method will update the amount of likes for a give post id.
  def self.update_likes_counter(id, likes_counter)
    count = likes_counter
    Post.where(id:).update(likes_counter: count)
  end

  # This method will take the Post Id as parameter and updated count value
  # It will increment the comments_counter by the given count value.
  def self.update_comments_counter(id, comments_counter)
    count = comments_counter
    Post.where(id:).update(comments_counter: count)
  end

  # Here we can reuse this code to find Posts that belongs to a user
  scope :posts_by_author_id, ->(author) { where(author:).order(created_at: 'DESC').first(3) }

  # Here It will call the method update_posts_counter that recides in the User Model.
  scope :update_posts_counter, ->(author, counter) { User.update_posts_counter(author, counter) }

  # Here we can call the method which recides in comments to find the 5 recent commnets for a post.
  def recent_posts_comment
    comments.order(created_at: 'DESC').limit(5)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApiController
  def index
    @post = Post.includes(:author, comments: [:author]).where(author: { id: params[:user_id] })
    render json: @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @post = Post.includes(:author, comments: [:author]).where(author: { id: params[:user_id] })
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @post }
    end
  end

  def new
    @user = current_user
    post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: } }
    end
  end

  def create
    @post = Post.new(params.require(:new_post).permit(:title, :text))
    user = current_user
    @post.author = user
    @post.comments_counter = 0
    @post.likes_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post successfully created'
          redirect_to user_path(user.id)
        else
          flash[:error] = 'Something Went Wrong one or more field is empty'
          post = Post.new
          respond_to do |f|
            f.html { redirect_to request.referrer, locals: { post: } }
          end
        end
      end
    end
  end

  def show
    @post = Post.includes(:author, comments: [:author]).where(author: { id: params[:user_id] }, id: params[:id]).first
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, status: :see_other
  end
end

app/views/posts/_post.html.erb
<%= link_to user_post_path(post.author.id,post.id), class:'post-link-container',id:post.id do %>
<div class="posts-list-container">
    <h4 class="post-title-header"><%= post.title %> </h4>
    <p class="posts-content">
        <%= post.text %>
    </p>
    <div class="interaction-container">
        <% if can? :delete, post %>
            <%= link_to 'Delete', post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_confirm: "Are you sure?" },class: 'counter counter-btn' %>
        <% end %>
        <%= link_to "Add Comment: #{post.comments_counter }" , new_post_comment_path(post.id), class: 'counter counter-btn' %>
        <%= button_to "Likes: #{post.likes_counter}", post_likes_path(post.id), method: :post, remote: true, class: 'counter counter-like-btn'  %>
    </div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="home-container">
<%= render @post[0].author %>


<% @post.each do |post|%>
<%= render post %>
<% if post.comments.length == 0 %>
<div class="comments-container">
    <h4>No comments</h4>
</div>
<% else %>
<div class="comments-container">
    <% post.recent_posts_comment.each do |comment|%>
    <%= render comment %>
    <% end %>
</div>
<% end %>
<% end %>

<div class="btn-container-post">
<%= link_to user_path(@post[0].author.id) do%>
<button class="btn-posts">Pagination</button>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="home-container">
<% flash.each do |type, msg| %>
  <% if type == "error" %>
    <div class="error-notice">
        <%= msg %>
    </div>
  <% end %>
<% end %>
<div class="form-container">
    <div class ="form-heading">
        <h3>Add New Post</h3>
    <div>
    <%= form_with model: post,method: :post, url: user_posts_path(@user.id), scope: :new_post,local:true do |form| %>
        <div>
            <%= form.label :title%>:
            <%= form.text_field :title %>
        </div>
        <div>
            <%= form.label :text %>:
            <br>
            <%= form.text_area :text %>
        </div>
        <%= form.submit "Add Post", disable_with: 'Submiting...' %>
    <% end %>
<div>
</div>

app/views/posts/show.html.erb
<div class="home-container">
<% flash.each do |type, msg| %>
  <% if type == "success" %>
    <div class="success-notice">
        <%= msg %>
    </div>
  <% end %>
<% end %>
<article class="posts-detail-container">
    <div class="post-info-container">
        <div class="post-info">
        <h5>Post</h5>
        <span>by <span><span class="poster-user-name"><%=  @post.author.name%></span>
        </div>
        <span class="post-title-header"><%= @post.title %></span>
        <div class="interaction-container-detail">
            <span class="comments-counter">Comments: <%= @post.comments_counter %></span>
            <span class="likes-counter">Likes: <%= @post.likes_counter %></span>
        </div>
    </div>
    <p class="post-content-article">
    <%= @post.text %>
    </p>
</article>
<% if @post.comments.length == 0 %>
<div class="comments-container">
    <h4>No comments</h4>
</div>
<% else %>
<div class="comments-container">
    <%= render @post.comments %>
</div>
<% end %>
</div>